"""Deliberate snapshot of the public beta naming surface."""

from __future__ import annotations

import latent_anything
from latent_anything import adapters, methods
from latent_anything.registry import KIND_ADAPTER, KIND_METHOD_A, KIND_METHOD_B


def test_top_level_public_beta_export_snapshot() -> None:
    assert latent_anything.__all__ == [
        "AnalysisPipeline",
        "BatchExecutor",
        "CacheKey",
        "CacheStats",
        "ClusterStabilityReport",
        "ConceptDataset",
        "ConceptDirectionResult",
        "ControlBaselines",
        "CovarianceConfig",
        "CovarianceState",
        "CrossSeedReport",
        "FeatureAtlas",
        "FeatureAtlasEntry",
        "FeatureCrossCheck",
        "FeatureRanking",
        "GLOBAL_REGISTRY",
        "InMemoryCache",
        "IntegratedGradients",
        "IntegratedGradientsConfig",
        "IntegratedGradientsResult",
        "KMeans",
        "KMeansConfig",
        "KMeansResult",
        "LatentSpace",
        "LatentValue",
        "LinearProbe",
        "LinearProbeConfig",
        "LinearProbeResult",
        "MLPProbe",
        "MLPProbeConfig",
        "MLPProbeResult",
        "ManipulationPipeline",
        "ManipulationPipelineSpec",
        "Method",
        "ObjectSpec",
        "OrthonormalSubspace",
        "PipelineResult",
        "PipelineSpec",
        "ProbeComparison",
        "SubspaceProjection",
        "SubspaceProjectionConfig",
        "TCAV",
        "TCAVConfig",
        "TCAVResult",
        "TCAVScore",
        "TransformerLogitTarget",
        "ProfileEvent",
        "Registry",
        "RegistryEntry",
        "RuntimeProfile",
        "RuntimeProfiler",
        "SAEConfig",
        "SAEEvaluationResult",
        "SAEFeatureEvaluation",
        "SAEFeatureMetrics",
        "SAEStabilityResult",
        "SensitivityReport",
        "Trajectory",
        "build_feature_atlas",
        "build_from_config",
        "build_from_dict",
        "build_manipulation_pipeline_from_config",
        "build_pipeline_from_config",
        "GMMConfig",
        "GaussianMixtureDensity",
        "DensityResult",
        "DensityMetrics",
        "DensityEvaluationReport",
        "DensityStabilityReport",
        "DensityGeodesic",
        "GeodesicConfig",
        "GeodesicPath",
        "PathOptimizationStatus",
        "density_cross_seed_evaluation",
        "mahalanobis_baseline",
        "fit_covariance_state",
        "check_clustering_geometry",
        "cluster_stability_analysis",
        "compare_probes",
        "compare_with_labels",
        "compute_integrated_gradients",
        "compute_tcav",
        "coordinate_identity",
        "assert_arithmetic_compatible",
        "cross_check_feature",
        "cross_seed_evaluation",
        "cross_seed_sae_stability",
        "evaluate_layers",
        "evaluate_sae_features",
        "evaluate_sensitivity",
        "intervention_agreement",
        "learn_linear_separator_direction",
        "learn_mean_diff_direction",
        "list_entries",
        "load_feature_atlas",
        "lookup_entry",
        "nonlinear_memorization_test",
        "rank_feature_examples",
        "register_entry",
        "save_feature_atlas",
    ]


def test_method_and_adapter_protocol_snapshot() -> None:
    assert methods.__all__ == ["ActivationPatch", "BMethod", "Method", "PCA", "SAE", "UMAP", "Lerp", "SteeringVector"]
    assert adapters.__all__ == [
        "ConvVAE",
        "DecodableAdapter",
        "FlatBatchDecodableAdapter",
        "GaussianRendererAdapter",
        "HiddenStateAdapter",
        "ModelAdapter",
        "RandomProjection",
        "VAE",
    ]


def test_registry_kind_snapshot() -> None:
    assert (KIND_ADAPTER, KIND_METHOD_A, KIND_METHOD_B) == ("adapter", "analysis", "intervention")
